name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Cache Composer Dependencies
        uses: actions/cache@v4.2.0
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Composer
        uses: php-actions/composer@v6
        with:
          dev: no
          php_version: 8.2

      - name: Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: '20'

      - name: Build Theme
        run: |
          corepack enable
          yarn install
          yarn build

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts

      - name: Rsync
        run: rsync -zar --progress --exclude "node_modules" --exclude ".env" --delete . ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:${{ secrets.REMOTE_PATH }}
